export const API = "https://pcmob6-blog-api.sylvieqian.repl.co"
export const API_LOGIN = "/auth"
export const API_SIGNUP = "/newuser"
export const API_POSTS = "/posts"
export const API_WHOAMI = "/whoami"
export const API_CREATE = "/create"
